[versions]
agp = "8.3.1"
coil = "2.6.0"
glide = "4.14.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
core = "1.7.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
uiGraphicsAndroid = "1.6.4"
palette = "1.0.0"
googleServices = "4.4.1"
firebaseFirestore = "25.0.0"
firebaseDatabase = "21.0.0"

[libraries]
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx = { group = "androidx.appcompat",name = "appcompat", version= "1.6.1" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
media = { module = "androidx.media:media", version = "1.4.1" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxCore = { group = "androidx.core", name = "core-ktx", version= "1.12.0" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version = "1.8.2" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.9.0" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofit2ConverterGson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.5.0" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0" }
okhttp3LoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.12.0" }
uuid = { group = "com.github.f4b6a3", name = "uuid-creator", version = "5.3.3" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

